// feedback 4:
// 자바스크립트 = application의 비즈니스 로직 담당
// 데이터가 함께 있으면 좋지 않음 => data.json
const data = [
  {
    gender: "female",
    size: "large",
    color: "pink",
    type: "tshirt",
    image: "pink_t.png",
  },
  {
    gender: "man",
    size: "small",
    color: "blue",
    type: "pants",
    image: "blue_p.png",
  },
  {
    gender: "man",
    size: "large",
    color: "yellow",
    type: "pants",
    image: "yellow_p.png",
  },
  {
    gender: "man",
    size: "large",
    color: "yellow",
    type: "skirt",
    image: "yellow_s.png",
  },
  {
    gender: "female",
    size: "small",
    color: "blue",
    type: "skirt",
    image: "blue_s.png",
  },
  {
    gender: "male",
    size: "large",
    color: "blue",
    type: "tshirt",
    image: "blue_t.png",
  },
  {
    gender: "male",
    size: "large",
    color: "yellow",
    type: "tshirt",
    image: "yellow_t.png",
  },
  {
    gender: "female",
    size: "small",
    color: "pink",
    type: "pants",
    image: "pink_p.png",
  },
  {
    gender: "female",
    size: "large",
    color: "pink",
    type: "tshirt",
    image: "pink_t.png",
  },
  {
    gender: "man",
    size: "small",
    color: "blue",
    type: "pants",
    image: "blue_p.png",
  },
  {
    gender: "man",
    size: "large",
    color: "yellow",
    type: "pants",
    image: "yellow_p.png",
  },
  {
    gender: "man",
    size: "large",
    color: "yellow",
    type: "skirt",
    image: "yellow_s.png",
  },
  {
    gender: "female",
    size: "small",
    color: "blue",
    type: "skirt",
    image: "blue_s.png",
  },
  {
    gender: "male",
    size: "large",
    color: "blue",
    type: "tshirt",
    image: "blue_t.png",
  },
  {
    gender: "male",
    size: "large",
    color: "yellow",
    type: "tshirt",
    image: "yellow_t.png",
  },
  {
    gender: "female",
    size: "small",
    color: "pink",
    type: "pants",
    image: "pink_p.png",
  },
];
